Global:
  debug: false
  interval: 10

Logging:
  logfile: '/var/log/pybeacon.log'
  loglevel: 'INFO'
  mark: true
  mark_count: 12
  list_devices_in_cfg: false
  print_on_load: false

Reporting:
  statsd:
    enabled: true
    host:    '127.0.0.1'
    port:    8125
    prefix:  'pybeacon'
  events:
      default:
        tick: false
      scan:
        tick: true
      packet:
        rx:
          unknown:
              tick: false

Beacons:
  eddystone:
    default:
      enabled: false
      report_telemetry: false
      report_telemetry_rate: false
      report_telemetry_uptime: false
      report_telemetry_voltage: true
      report_telemetry_temp: true
      report_telemetry_bytes: false
      report_uid_rate: false
      report_rssi: false
      native_temp_unit: 'c'
      output_temp_unit: 'f'
    devices:
      DF0A6A74BFDD:
        name: 'barn_ext'
        enabled: true
        report_telemetry: true
        report_rssi: true
      E515AAE053F5:
        name: 'workoutlandia'
        enabled: true
        report_telemetry: true
  estimote:
    default:
      enabled: false
      report_telemetry: false
    devices:
      AAAAAAAAAAAA:
          name: 'test'
