Global:
  debug: false
  sleep_time: 5
  scan_duration: 10
  maintain_statefile: true
  statefile: '/tmp/statefile.txt'
Logging:
  logfile: '/var/log/pybtsteward.log'
  loglevel: 'INFO'
  mark: true
  mark_count: 12
  list_devices_in_cfg: false
  print_on_load: false
  decode_eddy_loglevel: 'INFO'

Reporting:
  statsd:
    enabled: true
    loglevel: 'INFO'
    enabletcp: false
    host:    '127.0.0.1'
    port:    8125
    prefix:  'BTsteward'
  events:
      default:
        tick: false
      scan:
        tick: true
      packet:
        rx:
          unknown:
              tick: false

Beacons:
  eddystone:
    default:
      enabled: false
      log_raw_packet: false
      print_raw_packet: false
      log_decoded_packet: false
      print_decoded_packet: false
      report_telemetry: false
      report_telemetry_rate: true
      report_telemetry_uptime: false
      report_telemetry_voltage: true
      report_telemetry_temp: true
      report_telemetry_bytes: false
      report_uid_rate: false
      report_uid_rssi: true
      uid_rssi_offset: -41
      native_temp_unit: 'c'
      output_temp_unit: 'f'
    devices:
      'AA:AA:AA:AA:AA:AA':
        name: 'eddy_one'
        enabled: true
        report_telemetry: true
      'BB:BB:BB:BB:BB:BB':
        name: 'eddy_two'
        enabled: true
        report_telemetry: true
  estimote:
    default:
      enabled: false
      report_telemetry: false
    devices:
      'AA:AA:AA:AA:AA:AA':
          name: 'esti_one'
