Global:
  debug: false
  interval: 10

Logging:
  logfile: '/var/log/pybeacon.log'
  loglevel: 'INFO'
  mark: true
  mark_count: 12

Reporting:
  statsd:
    enabled: true
    host:    '127.0.0.1'
    port:    8125
    prefix:  ''
Beacons:
  eddystone:
    default:
      enabled: false
      report_telemetry: false
      report_rssi: false
      native_temp_unit: 'c'
    devices:
    - 'DF:0A:6A:74:BF:DD':
        name: 'barn_ext'
        enabled: true
        report_telemetry: true
        report_rssi: true
        native_temp_unit: 'c'
    - 'E5:15:AA:E0:53:F5':
        name: 'workoutlandia'
        enabled: true
  estimote:
      default:
        enabled: false
        report_telemetry: false
      devices:
        -'sample':
            mac: 'AA:AA:AA:AA:AA:AA'
